/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ProfilsRouteImport } from './routes/profils'
import { Route as RecompensesRouteImport } from './routes/recompenses'
import { Route as EnfantNouveauRouteImport } from './routes/enfant/nouveau'
import { Route as LeconLessonIdRouteImport } from './routes/lecon/$lessonId'
import { Route as MatieresIndexRouteImport } from './routes/matieres/index'
import { Route as MatieresSubjectIdRouteImport } from './routes/matieres/$subjectId'
import { Route as SequenceSequenceIdRouteImport } from './routes/sequence/$sequenceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilsRoute = ProfilsRouteImport.update({
  id: '/profils',
  path: '/profils',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensesRoute = RecompensesRouteImport.update({
  id: '/recompenses',
  path: '/recompenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantNouveauRoute = EnfantNouveauRouteImport.update({
  id: '/enfant/nouveau',
  path: '/enfant/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconLessonIdRoute = LeconLessonIdRouteImport.update({
  id: '/lecon/$lessonId',
  path: '/lecon/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresIndexRoute = MatieresIndexRouteImport.update({
  id: '/matieres/',
  path: '/matieres/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresSubjectIdRoute = MatieresSubjectIdRouteImport.update({
  id: '/matieres/$subjectId',
  path: '/matieres/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SequenceSequenceIdRoute = SequenceSequenceIdRouteImport.update({
  id: '/sequence/$sequenceId',
  path: '/sequence/$sequenceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/bienvenue': typeof BienvenueRoute
  '/classement': typeof ClassementRoute
  '/connexion': typeof ConnexionRoute
  '/otp': typeof OtpRoute
  '/profils': typeof ProfilsRoute
  '/recompenses': typeof RecompensesRoute
  '/enfant/nouveau': typeof EnfantNouveauRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
  '/matieres/$subjectId': typeof MatieresSubjectIdRoute
  '/sequence/$sequenceId': typeof SequenceSequenceIdRoute
  '/matieres/': typeof MatieresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/bienvenue': typeof BienvenueRoute
  '/classement': typeof ClassementRoute
  '/connexion': typeof ConnexionRoute
  '/otp': typeof OtpRoute
  '/profils': typeof ProfilsRoute
  '/recompenses': typeof RecompensesRoute
  '/enfant/nouveau': typeof EnfantNouveauRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
  '/matieres/$subjectId': typeof MatieresSubjectIdRoute
  '/sequence/$sequenceId': typeof SequenceSequenceIdRoute
  '/matieres': typeof MatieresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/bienvenue': typeof BienvenueRoute
  '/classement': typeof ClassementRoute
  '/connexion': typeof ConnexionRoute
  '/otp': typeof OtpRoute
  '/profils': typeof ProfilsRoute
  '/recompenses': typeof RecompensesRoute
  '/enfant/nouveau': typeof EnfantNouveauRoute
  '/lecon/$lessonId': typeof LeconLessonIdRoute
  '/matieres/$subjectId': typeof MatieresSubjectIdRoute
  '/sequence/$sequenceId': typeof SequenceSequenceIdRoute
  '/matieres/': typeof MatieresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/bienvenue'
    | '/classement'
    | '/connexion'
    | '/otp'
    | '/profils'
    | '/recompenses'
    | '/enfant/nouveau'
    | '/lecon/$lessonId'
    | '/matieres/$subjectId'
    | '/sequence/$sequenceId'
    | '/matieres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/bienvenue'
    | '/classement'
    | '/connexion'
    | '/otp'
    | '/profils'
    | '/recompenses'
    | '/enfant/nouveau'
    | '/lecon/$lessonId'
    | '/matieres/$subjectId'
    | '/sequence/$sequenceId'
    | '/matieres'
  id:
    | '__root__'
    | '/'
    | '/accueil'
    | '/bienvenue'
    | '/classement'
    | '/connexion'
    | '/otp'
    | '/profils'
    | '/recompenses'
    | '/enfant/nouveau'
    | '/lecon/$lessonId'
    | '/matieres/$subjectId'
    | '/sequence/$sequenceId'
    | '/matieres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccueilRoute: typeof AccueilRoute
  BienvenueRoute: typeof BienvenueRoute
  ClassementRoute: typeof ClassementRoute
  ConnexionRoute: typeof ConnexionRoute
  OtpRoute: typeof OtpRoute
  ProfilsRoute: typeof ProfilsRoute
  RecompensesRoute: typeof RecompensesRoute
  EnfantNouveauRoute: typeof EnfantNouveauRoute
  LeconLessonIdRoute: typeof LeconLessonIdRoute
  MatieresSubjectIdRoute: typeof MatieresSubjectIdRoute
  SequenceSequenceIdRoute: typeof SequenceSequenceIdRoute
  MatieresIndexRoute: typeof MatieresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profils': {
      id: '/profils'
      path: '/profils'
      fullPath: '/profils'
      preLoaderRoute: typeof ProfilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompenses': {
      id: '/recompenses'
      path: '/recompenses'
      fullPath: '/recompenses'
      preLoaderRoute: typeof RecompensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfant/nouveau': {
      id: '/enfant/nouveau'
      path: '/enfant/nouveau'
      fullPath: '/enfant/nouveau'
      preLoaderRoute: typeof EnfantNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecon/$lessonId': {
      id: '/lecon/$lessonId'
      path: '/lecon/$lessonId'
      fullPath: '/lecon/$lessonId'
      preLoaderRoute: typeof LeconLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres/': {
      id: '/matieres/'
      path: '/matieres'
      fullPath: '/matieres/'
      preLoaderRoute: typeof MatieresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres/$subjectId': {
      id: '/matieres/$subjectId'
      path: '/matieres/$subjectId'
      fullPath: '/matieres/$subjectId'
      preLoaderRoute: typeof MatieresSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequence/$sequenceId': {
      id: '/sequence/$sequenceId'
      path: '/sequence/$sequenceId'
      fullPath: '/sequence/$sequenceId'
      preLoaderRoute: typeof SequenceSequenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccueilRoute: AccueilRoute,
  BienvenueRoute: BienvenueRoute,
  ClassementRoute: ClassementRoute,
  ConnexionRoute: ConnexionRoute,
  OtpRoute: OtpRoute,
  ProfilsRoute: ProfilsRoute,
  RecompensesRoute: RecompensesRoute,
  EnfantNouveauRoute: EnfantNouveauRoute,
  LeconLessonIdRoute: LeconLessonIdRoute,
  MatieresSubjectIdRoute: MatieresSubjectIdRoute,
  SequenceSequenceIdRoute: SequenceSequenceIdRoute,
  MatieresIndexRoute: MatieresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
