/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as OtpRouteImport } from './routes/otp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/otp': typeof OtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/otp': typeof OtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/otp': typeof OtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bienvenue' | '/connexion' | '/otp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bienvenue' | '/connexion' | '/otp'
  id: '__root__' | '/' | '/bienvenue' | '/connexion' | '/otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienvenueRoute: typeof BienvenueRoute
  ConnexionRoute: typeof ConnexionRoute
  OtpRoute: typeof OtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienvenueRoute: BienvenueRoute,
  ConnexionRoute: ConnexionRoute,
  OtpRoute: OtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
